/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ScannerCode;
  import java.util.Scanner;
public class App {
    

    public static void main(String[] args) {
    
        Scanner scanner = new Scanner(System.in);

        // Get student information
        System.out.print("Enter Student Number: ");
        int studentNumber = scanner.nextInt();
        scanner.nextLine(); // consume the newline character

        System.out.print("Enter Name: ");
        String name = scanner.nextLine();

        System.out.print("Enter Surname: ");
        String surname = scanner.nextLine();

        System.out.print("Enter Email: ");
        String email = scanner.nextLine();

        System.out.print("Enter Phone Number: ");
        String phoneNumber = scanner.nextLine();

        // Get marks
        System.out.print("Enter Mark 1: ");
        double mark1 = scanner.nextDouble();

        System.out.print("Enter Mark 2: ");
        double mark2 = scanner.nextDouble();

        System.out.print("Enter Assignment Mark: ");
        double assignmentMark = scanner.nextDouble();

        System.out.print("Enter Exam Mark: ");
        double examMark = scanner.nextDouble();
        
        // Calculate final mark
        double DpMark = CalculateDpMark(mark1, mark2, assignmentMark);
        // Calculate final mark
        double finalMark = calculateFinalMark(DpMark, examMark);

        // Display student information and final mark
        System.out.println("\nStudent Information:");
        System.out.println("Student Number: " + studentNumber);
        System.out.println("Name: " + name);
        System.out.println("Surname: " + surname);
        System.out.println("Email: " + email);
        System.out.println("Phone Number: " + phoneNumber);

        System.out.println("\nMarks:");
        System.out.println("Mark 1: " + mark1);
        System.out.println("Mark 2: " + mark2);
        System.out.println("Assignment Mark: " + assignmentMark);
        System.out.println("Exam Mark: " + examMark);

        System.out.println("\nDuly Performed Mark : " + DpMark);
        System.out.println("Final Mark: " + finalMark);

        // Close the scanner to prevent resource leak
        scanner.close();
    }
     private static double CalculateDpMark(double mark1, double mark2, double assignmentMark) {
        return (mark1 + mark2 + assignmentMark)/3;
     }

    // Method to calculate the final mark based on a simple formula
    private static double calculateFinalMark(double DpMark , double examMark) {
        return ((DpMark * 0.4) + (examMark * 0.6));
    }
}
